---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.7
- name: centos-5.11
- name: debian-8.2
suites:
- name: default
  run_list: ["recipe[r]"]
  attributes: {}
