sudo: false
rvm:
  - 2.2
before_install:
  - gem update --system
  - gem --version
script:
  - bundle exec foodcritic -f any .
  - bundle exec rspec --color --format progress
  - bundle exec rubocop -l
